### ISSUE TITLE
JS Templating

### ISSUE THREAD

**Issue by internetllama** [MonikaaS/web-app-from-scratch-18-19#3]
Misschien kun je kijken naar JS Templating?
Een voorbeeld hiervan is in mijn code (https://github.com/internetllama/web-app-from-scratch-18-19/blob/master/week1/public/js/app.js)

https://github.com/MonikaaS/web-app-from-scratch-18-19/blob/a2c42aedec129dec49274b1a5d3c7e4c84b6842b/week1/public/js/app.js#L21-L33

**Comment by maanlamp** [comment]
@internetllama Templating is zeker handig, maar je moet eigenlijk geen `Element.innerHTML` gebruiken. @MonikaaS Als je hier echt mee aan de slag wil gaan zou ik een (goede?) templating engine zoeken!

**Comment by MonikaaS** [comment]
https://github.com/MonikaaS/web-app-from-scratch-18-19/blob/fb5a267ac7481cfafd3bffed2fbf6a04189cd6a3/week2/public/js/app.js#L8-L17
