### ISSUE TITLE
Use proper .onerror method

### ISSUE THREAD

**Issue by maanlamp** [MonikaaS/web-app-from-scratch-18-19#4]
https://github.com/MonikaaS/web-app-from-scratch-18-19/blob/a2c42aedec129dec49274b1a5d3c7e4c84b6842b/week1/public/js/app.js#L38

An XHR has a `.onerror` method that will run if it encounters an error. This way you can log the actual error instead of `"error"` :)

**Comment by MonikaaS** [comment]
https://github.com/MonikaaS/web-app-from-scratch-18-19/blob/eccc51e464b84654f5c7961eda19f3d53563d22c/week2/public/js/app.js#L31
