### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by TuriGuilano** [MonikaaS/web-app-from-scratch-18-19#6]
Try to avoid global scope:

https://github.com/MonikaaS/web-app-from-scratch-18-19/blob/a2c42aedec129dec49274b1a5d3c7e4c84b6842b/week1/public/js/app.js#L4

https://github.com/MonikaaS/web-app-from-scratch-18-19/blob/a2c42aedec129dec49274b1a5d3c7e4c84b6842b/week1/public/js/app.js#L6

See other variables as well.

**Comment by MonikaaS** [comment]
https://github.com/MonikaaS/web-app-from-scratch-18-19/blob/7ce781954b4a179ef702768e103138be9f0281a7/week2/public/js/app.js#L2-L7
