### ISSUE TITLE
var / let / const

### ISSUE THREAD

**Issue by TuriGuilano** [MonikaaS/web-app-from-scratch-18-19#7]
You use const regularly but occasionally also a var, why? Make sure to understand what the difference is between those three and when to use which one. 

https://github.com/MonikaaS/web-app-from-scratch-18-19/blob/a2c42aedec129dec49274b1a5d3c7e4c84b6842b/week1/public/js/app.js#L6

https://github.com/MonikaaS/web-app-from-scratch-18-19/blob/a2c42aedec129dec49274b1a5d3c7e4c84b6842b/week1/public/js/app.js#L11

**Comment by MonikaaS** [comment]
fixed it:

https://github.com/MonikaaS/web-app-from-scratch-18-19/blob/7ce781954b4a179ef702768e103138be9f0281a7/week2/public/js/app.js#L4-L5

https://github.com/MonikaaS/web-app-from-scratch-18-19/blob/7ce781954b4a179ef702768e103138be9f0281a7/week2/public/js/app.js#L21
